# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkoutArena' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorkoutArena

  pod 'SnapKit'
  pod 'Alamofire'
end

target 'TriviaIntent' do
 use_frameworks!
 pod 'Alamofire'
end